name: sample-run

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - name: Build Keploy
        run: |
          go build -v ./...

      - name: Build arm 
        run: GOOS=linux GOARCH=arm64 go build -v ./...